# Generated by Django 4.1.3 on 2022-12-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_catagory_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
    ]
